/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


#include <stdint.h>

#include "FreeRTOS.h"
#include "task.h"

#define STACK_SIZE 200
static StaticTask_t TaskBuffer;
static StackType_t xStack[ STACK_SIZE ];

static void vTaskCode(void * ptr)
{
	while(1)
	{
		vTaskDelay(1000);
	}
}

int main(void)
{
	// Tasks can be created before or after starting the RTOS scheduler

	xTaskCreateStatic(vTaskCode, "TEST", STACK_SIZE, NULL, tskIDLE_PRIORITY+1, xStack, &TaskBuffer);

	vTaskStartScheduler();

    /* Loop forever */
	for(;;);
}
